/*input
20 20
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
*/
#include<bits/stdc++.h>
using namespace std;
const int mod = 1e9+7;
int n,m;
vector<string> mat;
vector<vector<int>> dp;

int fun(int x,int y)
{
	if(x<0 || x>=n || y<0 || y>=m) return 0;
	if(dp[x][y]!=-1) return dp[x][y];
	if(mat[x][y]=='#') return dp[x][y]=0;
	if(x==0 && y==0) return dp[x][y]=1;
	int ans = (fun(x-1,y) + fun(x,y-1))%mod;
	return dp[x][y]=ans;
}

int main()
{
	cin>>n>>m;
	mat.resize(n);
	dp.assign(n,vector<int> (m,-1));
	for(int i=0;i<n;i++)
	{
		string s;cin>>s;
		mat[i]=s;
	}
	cout<<fun(n-1,m-1)<<"\n";
	return 0;
}
